config/routes.rb
Btlshp::Application.routes.draw do

  resources :games

  match 'help' => 'help#index'
  match 'about' => 'help#about'
  match 'hof' => 'scores#index'

  root :to => 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def log(who, x, y, result)
    "<b>#{h who}</b> fired at #{h x}, #{h y} and <b>#{h result}</b>".html_safe
  end
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_navbar.html.haml
/todo this should be in a partial somewhere
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      .row
        .span10.offset1
          = link_to 'Battleship', '#', :class => 'brand'
          %ul.nav.pull-left
            %li.active
              = link_to 'Game', games_path
            %li.dropdown
              %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
                History
                %b.caret
              %ul.dropdown-menu
                %li.nav-header Recent games
                %li= link_to 'Recent game #1', game_path(:id => 1)
                %li= link_to 'Recent game #2', game_path(:id => 1)
                %li= link_to 'Recent game #3', game_path(:id => 1)
                %li.divider
                %li= link_to 'More...', '#'
            %li= link_to 'Hall of Fame', hof_path
            %li= link_to 'Help', help_path
            %li= link_to 'About', about_path
          %ul.nav.pull-right
            %li= link_to 'Sign out', '/'

app/views/games/index.html.haml
- content_for :navbar do
  = render :partial => 'navbar'

.row
  .span5.offset1
    %h1 Game with XYZ
    %h3#status-head Prepare for battle
  .span5.user-label
    %p Signed in as Ninja Burger
.row
  .span10.offset1
    %hr
    #board-tabs.tabbable
      %ul.nav.nav-tabs
        %li#remote= link_to "XYZ's board", '#show_remote'
        %li#local.active= link_to "Your board", '#show_local'
    #game-canvas
      /noempty
    #game-info
      #game-prepare
        .info-head
          %strong Prepare your fleet!
        .info-section
          Drag the ships into the battlefield using your mouse.
          Valid squares are green.
          %br
          Double click to rotate a ship (only works in staging area).
        .info-section
          = link_to 'Start game', '#', :class => 'btn btn-success disabled', :id => 'start-btn'
        .info-section
          = link_to 'Place ships (debug)', '#', :class => 'btn', :id => 'debug-ships'
      #game-status
        .info-head Your status
        .info-count
          %strong
            Ships left:
            %span#ship-count
        .info-count
          Carriers:
          %span#carrier-count
        .info-count
          Battleships:
          %span#battleship-count
        .info-count
          Destroyers:
          %span#destroyer-count
        .info-count
          Subs:
          %span#sub-count
        .info-section
          .info-head Game history
          .well
            %ul#game-log
        .info-section
          = link_to 'Admit defeat', '#', :class => 'btn btn-danger'
      #throbber.info-section
        = image_tag 'throbber.gif'
        %span Gathering intel...

.row
  .span10.offset1
    %hr
    %p Maybe a chat area? (if there is time)

app/views/games/show.html.haml
- content_for :navbar do
  = render :partial => 'navbar'

.row
  .span5.offset1
    %h1 Game with XYZ - Replay
    %h3 You won!
  .span5.user-label
    %p Signed in as Ninja Burger
.row
  .span10.offset1
    %hr
    .tabbable
      %ul.nav.nav-tabs
        %li.active= link_to "XYZ's board", '#remote', 'data-toggle' => 'tab'
        %li= link_to "Your board", '#local', 'data-toggle' => 'tab'
      .tab-content
        #remote.tab-pane.active
          /empty
        #local.tab-pane
          /empty
    #game-canvas
      /noempty
    #reply-panel
      .info-head Turn 4
      .info-history
        .info-head Game history
        .well
          %ul
            %li= log('XYZ', 3, 5, 'missed')
            %li= log('You', 4, 4, 'you hit!')
            %li= log('<b>XSS</b>', 5, 5, 'test') 
            %li more log lines...
            %li more log lines...
            %li lorem
            %li ipsum
            %li etc
      .btn-group
        .btn= link_to 'Previous', '#'
        .btn= link_to 'Resume replay', '#'
        .btn= link_to 'Next', '#'
.row
  .span10.offset1
    %hr
    %p Maybe a chat history area? (if there is time)

app/views/help/about.html.haml
- content_for :navbar do
  = render :partial => 'navbar'

.row
  .span5.offset1
    %h1 About
  .span5.user-label
    %p Signed in as Ninja Burger

.row
  .span10.offset1
    %hr

.row
  .span7.offset1
    %strong About lead
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum arcu sed nunc condimentum luctus. Suspendisse potenti. Nunc rutrum neque vel augue pulvinar tristique. Integer id mauris velit, vitae consectetur nulla. Nulla augue arcu, aliquam et condimentum nec, hendrerit a ipsum. Aliquam auctor gravida sodales. Nunc fermentum vestibulum est, eu viverra ligula imperdiet eu. Pellentesque ac mauris turpis, a vehicula magna. Praesent non lorem augue. In felis augue, aliquam quis facilisis et, elementum sit amet leo. Suspendisse vitae mi magna, in commodo diam.

app/views/help/index.html.haml
- content_for :navbar do
  = render :partial => 'navbar'

.row
  .span5.offset1
    %h1 Help
  .span5.user-label
    %p Signed in as Ninja Burger

.row
  .span10.offset1
    %hr

.row
  .span8.offset1
    %h3 Topic 1
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum arcu sed nunc condimentum luctus. Suspendisse potenti. Nunc rutrum neque vel augue pulvinar tristique. Integer id mauris velit, vitae consectetur nulla. Nulla augue arcu, aliquam et condimentum nec, hendrerit a ipsum. Aliquam auctor gravida sodales. Nunc fermentum vestibulum est, eu viverra ligula imperdiet eu. Pellentesque ac mauris turpis, a vehicula magna. Praesent non lorem augue. In felis augue, aliquam quis facilisis et, elementum sit amet leo. Suspendisse vitae mi magna, in commodo diam.
    %h3 Topic 2
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum arcu sed nunc condimentum luctus. Suspendisse potenti. Nunc rutrum neque vel augue pulvinar tristique. Integer id mauris velit, vitae consectetur nulla. Nulla augue arcu, aliquam et condimentum nec, hendrerit a ipsum. Aliquam auctor gravida sodales. Nunc fermentum vestibulum est, eu viverra ligula imperdiet eu. Pellentesque ac mauris turpis, a vehicula magna. Praesent non lorem augue. In felis augue, aliquam quis facilisis et, elementum sit amet leo. Suspendisse vitae mi magna, in commodo diam.
    %h3 Topic 3
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum arcu sed nunc condimentum luctus. Suspendisse potenti. Nunc rutrum neque vel augue pulvinar tristique. Integer id mauris velit, vitae consectetur nulla. Nulla augue arcu, aliquam et condimentum nec, hendrerit a ipsum. Aliquam auctor gravida sodales. Nunc fermentum vestibulum est, eu viverra ligula imperdiet eu. Pellentesque ac mauris turpis, a vehicula magna. Praesent non lorem augue. In felis augue, aliquam quis facilisis et, elementum sit amet leo. Suspendisse vitae mi magna, in commodo diam.
  .span2.help_contents
    %h4 Contents
    %ul.nav.nav-tabs.nav-stacked
      %li= link_to 'Topic 1', '#'
      %li= link_to 'Topic 2', '#'
      %li= link_to 'Topic 3', '#'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Btlshp
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:onmousedown => 'return false;'}

    %a{:href => "http://github.com/madisp/btlshp"}
      /nice URI, github.
      - src = "https://a248.e.akamai.net/assets.github.com/img/5d21241b64dc708fcbb701f68f72f41e9f1fadd6/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f7265645f6161303030302e706e67"
      %img.github{:src => src, :alt => "Fork me on github"}

    #navigation-content
      = yield :navbar
    #main-content.container
      = yield
    #footer.container
      .row
        .span8.offset1 2012 / Tartu Ülikool / Veebirakenduste loomine / Madis Pink
        .span2.version Static version.

app/views/layouts/landing.html.haml
!!! 5
%html
  %head
    %title Btlshp
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #main-content.container
      = yield

app/views/scores/index.html.haml
- content_for :navbar do
  = render :partial => 'navbar'

.row
  .span5.offset1
    %h1 Hall of Fame
  .span5.user-label
    %p Signed in as Ninja Burger

.row
  .span10.offset1
    %hr

.row
  .span7.offset1
    %table.hof-table
      %tr
        %th User
        %th Wins
        %th Losses
      %tr
        %td XYZ
        %td 5
        %td 0
      %tr
        %td Ninja Burger (That's you!)
        %td 4
        %td 1

app/views/welcome/index.html.haml
.landing.row
  .span8.offset2
    .hero-unit
      %h1 Battleship
      %p A school project concerning naval warfare.
      = link_to 'Sign in', games_path, :class => 'btn btn-primary btn-large'